export const ROUTES = {
  HOME: "/",
  EXPLORE: "/explore",
  DESTINATION: "/destination/:id",
  PLANNER: "/planner",
  DASHBOARD: "/dashboard",
  TRIP_DETAIL: "/itineraries/:id",
  ITINERARIES: "/itineraries",
  BLOGS: "/blogs",
  ABOUT: "/about",
  CONTACT: "/contact",
  LOGIN: "/login",
  SIGNUP: "/signup",
  PROFILE: "/profile",
};
